# Pseudocode

See https://www.youtube.com/watch?v=4G0EYfrrDT8 for a reasonable introduction to pseudocode.

Writing code without thinking of its architecture is useless in the same way as dreaming about your desires without a plan of achieving them. Before writing the first line of code, you should understand what it will be doing, how it will do it, which modules and services it will use and how they will work together, what structure it will have, how it will be tested and debugged, and how it will be updated. - *paraphrased from quote by Andrey Nikishaev*


---
## Bubble Sort Algorithm

Sort a list of items by repeatedly swapping pairs of items that are out of order until the list is sorted.

But how will you do it? That's the point of pseudocode.

![Bubble Sort](images/bubblesort.png)

## <font color=red>Exercise</font>

1. Write a very brief description of how you will implement the bubble sort algorithm.

2. Write pseudocode for the bubble sort algorithm.

3. Write a function that implements the bubble sort algorithm on an input array and use it to sort the list of items below.

In [1]:
import numpy as np
items = np.random.randint(0, 10, (20,))
items

array([9, 7, 8, 3, 0, 4, 2, 0, 7, 3, 7, 3, 9, 1, 8, 1, 0, 0, 0, 2])

In [2]:
def bubblesort(items):
    numItems = len(items)
    isSorted = False
    while not isSorted:
        isSorted = True  # assume sorted unless we have to swap during this loop
        for i in range(numItems-1):
            if items[i+1] < items[i]:  # items out of order
                items[i], items[i+1] = items[i+1], items[i]  # swap items
                isSorted = False  # we swapped, so we're not sorted yet

In [3]:
bubblesort(items)
items

array([0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 4, 7, 7, 7, 8, 8, 9, 9])

---
## Insertion Sort Algorithm

For each item in an list, insert it into its sorted position within all previous items.

![Insertion Sort](images/insertionsort.png)

## <font color=red>Exercise</font>

1. Write a very brief description of how you will implement the insertion sort algorithm.

2. Write pseudocode for the insertion sort algorithm.

3. Write a function that implements the insertion sort algorithm on an input array and use it to sort the list of items below.

In [1]:
import numpy as np
items = np.random.randint(0, 10, (20,))
items

array([2, 2, 4, 6, 5, 3, 2, 7, 8, 6, 9, 5, 4, 1, 2, 3, 8, 1, 1, 2])

In [2]:
def insertionSort(items):
    for i in range(1, len(items)):
        for j in range(i, 0, -1):
            if items[j-1] > items[j]:
                items[j-1], items[j] = items[j], items[j-1]
            else:
                break

In [3]:
insertionSort(items)
items

array([1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 8, 8, 9])